version: "3"
services:
  apiService:
    image: 'clr.messageservice.webapi:v1'
    container_name: myapi
    ports:
      - "5000:80"
    deploy:
      restart_policy:
        condition: always
    build:
      context: .
      dockerfile: dockerfile.webapi
    links:
      - influxdb
    depends_on:
      - influxdb
  influxdb:
    image: 'influxdb'
    container_name: myinfluxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
    deploy:
      restart_policy:
        condition: always 
  grafana:
    image: 'grafana/grafana'
    container_name: mygrafana
    ports:
      - "3000:3000"
    deploy:
      restart_policy:
        condition: always  
    links:
      - influxdb
    depends_on:
      - influxdb
  mysql:
    image: 'mysql'
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: a@12345
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
      - ./conf/my.cnf:/etc/my.cnf
    deploy:
      restart_policy:
        condition: always